; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "AI_Nuclei_Detection"
#define MyAppVersion "1.0"
#define MyAppPublisher "BFM"
#define MyAppURL "https://bfm.rcbe.de"
#define MyAppExeName "AI_Nuclei_Detection.exe"
#define MyAppAssocName MyAppName + " Installer"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8EC62A38-CDD9-4512-9C46-BB73CC718813}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
PrivilegesRequired=lowest
OutputDir=C:\Users\pod38798\Documents\GITHUB\AI-Nuclei-Detection\app\distribution\Installer
OutputBaseFilename=AI_Nuclei_Detection_Installer
SetupIconFile=C:\Users\pod38798\Documents\GITHUB\AI-Nuclei-Detection\app\icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern   
DiskSpanning=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\pod38798\Documents\GITHUB\AI-Nuclei-Detection\app\output\AI_Nuclei_Detection\AI_Nuclei_Detection.exe"; DestDir: "{app}"; Flags: ignoreversion
;Source: "C:\Users\pod38798\Documents\GITLAB\AI_Nuclei_Detection\ai-nuclei-detection\output\AI_Nuclei_Detection\AI_Nuclei_Detection_Console.exe"; DestDir: "{app}"; Flags: ignoreversion
;Source: "C:\Users\pod38798\Documents\GITLAB\AI_Nuclei_Detection\ai-nuclei-detection\application_resources\*"; DestDir: "{app}\application_resources"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\pod38798\Documents\GITHUB\AI-Nuclei-Detection\app\output\AI_Nuclei_Detection\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\pod38798\Documents\GITHUB\AI-Nuclei-Detection\app\gui\*"; DestDir: "{app}\gui"; Flags: ignoreversion recursesubdirs createallsubdirs
;Source: "C:\Users\pod38798\Documents\GITLAB\AI_Nuclei_Detection\ai-nuclei-detection\settings.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\pod38798\Documents\GITHUB\AI-Nuclei-Detection\app\icon.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

